blog/blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
# 我们这里导入了一个 include 函数，然后利用这个函数把 blog 应用下的 urls.py 文件包含了进来。此外 include 前还有一个 r''，这是一个空字符串。这里也可以写其它字符串，Django 会把这个字符串和后面 include 的 urls.py 文件中的 URL 拼接。比如说如果我们这里把 r'' 改成 r'blog/'，而我们在 blog.urls 中写的 URL 是 r'^$'，即一个空字符串。那么 Django 最终匹配的就是 blog/ 加上一个空字符串，即 blog/。
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('myblog.urls')),
    url(r'', include('comments.urls')),
]

blog/myblog/urls.py
from django.conf.urls import url
from . import views
import re

# 指定这个urls.pyshi属于‘myblog’应用的，这种技术叫视图函数的命名空间
app_name = 'myblog'
urlpatterns = [
    # url(r'^$',views.index,name='index'),
    # as_view 方法,将类视图转换为函数视图
    # url(r'^category/(?P<pk>[0-9]+)/$',views.category, name='category'),
    url(r'^$',views.IndexView.as_view(),name='index'),
    url(r'^contact/$',views.contact,name='contact'),
    url(r'^category/(?P<pk>[0-9]+)/$',views.CategoryView.as_view(), name='category'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',views.ArchivesView.as_view(),name='archives'),
    url(r'^article/(?P<pk>[0-9]+)/$', views.ArticleDetailView.as_view(), name='detail'),
    url(r'^tag/(?P<pk>[0-9]+)/$',views.tag, name='tag'),
    url(r'^search/$', views.search, name='search'),

]

blog/templates/base.html
<!DOCTYPE html>
<html>
<head>
    {% load staticfiles %}
    {% load blog_tags %}
    <title>DuanHao-Space</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <!--<link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">-->
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/index.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/date.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/date_style.css' %}">
    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <!--<script src="{% static 'blog/js/bootstrap.min.js' %}"></script>-->
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
    <script src="{% static 'blog/js/prefixfree.min.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'myblog:index' %}"><span id="My"></span><b>My</b></span>Space</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'myblog:index'%}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="{% url 'myblog:index'%}" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="{% url 'myblog:contact'%}" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'myblog:search' %}">
                            <input type="search" name="q" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>

  <!--style="background-image: url({% static "blog/img/background.jpg" %});"-->
<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-4">
                {% block toc %}
                {% endblock toc %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_articles as recent_article_list %}
                    <ul>
                        {% for article in recent_article_list %}
                        <li>
                            <span style="color:#999999;"><i class="fa fa-list-ul" aria-hidden="true"></i></span><a href="{{ article.get_absolute_url}}"> {{ article.title }}</a>
                        </li>
                        {% empty %}
                        暂无文章
                        {% endfor %}
                    </ul>
                </div>

                <!--<div class="widget widget-archives">-->
                    <!--<h3 class="widget-title">归档</h3>-->
                    <!--{% get_archives as date_list %}-->
                    <!--<ul>-->
                        <!--{% for date in date_list %}-->
                        <!--<li>-->
                            <!--<span style="color:#999999;"><i class="fa fa-calendar" aria-hidden="true"></i></span><a href="{% url 'myblog:archives' date.year date.month %}"> {{ date.year }}年{{ date.month }}月</a>-->
                        <!--</li>-->
                        <!--{% endfor %}-->
                    <!--</ul>-->

                <!--</div>-->

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_category as category_list %}
                    <ul>
                        {% for category in category_list %}
                        <li>
                            <span style="color:#999999;"><i class="fa fa-bookmark" aria-hidden="true"></i></span><a href="{% url 'myblog:category' category.pk %}"> {{ category.name }}<span class="post-count">({{ category.num_articles }})</span></a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div id="datepicker" class="calendar"></div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签</h3>
                    {% get_tags as tags_list %}
                    <ul>
                        {% for tag in tags_list %}
                        <li>
                            <a href="{% url 'myblog:tag' tag.pk %}">{{ tag.name }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-admin">
                    <h3 class="widget-title">管理员</h3>
                    <span class="admin" style="color:#999999;"><i class="fa fa-user" aria-hidden="true"></i> <a href="http://118.24.27.191/admin/">后台管理</a></span>
                </div>

            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - <a href="#">段浩</a>
                    - <a href="#">MySpace</a>
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>
<script src="{% static 'blog/js/jquery-ui.js' %}"></script>
<script src="{% static 'blog/js/date.js' %}"></script>

</body>
</html>